
REM ----------------------------------------
REM  Remove files generated by the compiler
REM ----------------------------------------

REM removing *.pdb files
del *.pdb /f /q /s

REM removing vshost.exe* files
del *.vshost.exe* /f /q /s

REM removing *.exe files from obj folder
del Sources\obj\*.exe /f /q /s


